-- Per-account export history: every detailed XLSX export is saved to
-- Storage and logged here so users can revisit/redownload past exports,
-- matching the auth pattern in 0005_saved_searches_auth.sql /
-- 0007_match_runs_auth.sql.

create table if not exists public.export_history (
    id uuid default gen_random_uuid() primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    name text not null,
    filters jsonb not null default '{}',
    row_count integer,
    storage_path text not null,
    file_size bigint,
    created_at timestamptz not null default now()
);

alter table public.export_history enable row level security;

drop policy if exists "select_own_export_history" on public.export_history;
create policy "select_own_export_history"
    on public.export_history for select
    using (user_id = auth.uid());

drop policy if exists "insert_own_export_history" on public.export_history;
create policy "insert_own_export_history"
    on public.export_history for insert
    with check (user_id = auth.uid());

drop policy if exists "delete_own_export_history" on public.export_history;
create policy "delete_own_export_history"
    on public.export_history for delete
    using (user_id = auth.uid());

-- Storage bucket for exported files. Private — every read goes through a
-- signed URL scoped to the owning user, generated by
-- /api/exports/[id]/download.
insert into storage.buckets (id, name, public)
values ('exports', 'exports', false)
on conflict (id) do nothing;

-- No `alter table storage.objects enable row level security` here — on
-- hosted Supabase that table is owned by an internal role, not the role SQL
-- editor sessions run as, so that statement fails with "must be owner of
-- table objects". RLS is already enabled on storage.objects by default on
-- every Supabase project, so it isn't needed anyway.

-- Path convention: {user_id}/{export_id}.xlsx — bucket_id is included in
-- every policy (not just the folder check) since storage.objects is a
-- single table shared across every bucket in the project.
drop policy if exists "select_own_export_files" on storage.objects;
create policy "select_own_export_files"
    on storage.objects for select
    using (
        bucket_id = 'exports'
        and (storage.foldername(name))[1] = auth.uid()::text
    );

drop policy if exists "insert_own_export_files" on storage.objects;
create policy "insert_own_export_files"
    on storage.objects for insert
    with check (
        bucket_id = 'exports'
        and (storage.foldername(name))[1] = auth.uid()::text
    );

drop policy if exists "delete_own_export_files" on storage.objects;
create policy "delete_own_export_files"
    on storage.objects for delete
    using (
        bucket_id = 'exports'
        and (storage.foldername(name))[1] = auth.uid()::text
    );
